### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Sony-1972** [Azona77/AHK-QuickCommand#1]
Is it possible to launch the command instantly If there is only One result found ?
Thank you for your script
I like it

**Comment by Azona77** [comment]
> Is it possible to launch the command instantly If there is only One result found ? Thank you for your script I like it

This feature is nice, but it may lead to accidentally triggering unwanted commands, so I think it's better to have it turned off by default.

I've added a simple implementation method. Please see the new commented lines in the UpdateListBox for details. If you need this feature, you can enable it by manually uncommenting:
- https://github.com/Azona77/AHK-QuickCommand/commit/a2ceff73faa240e22ffdbb27c1ed38d4cb68d660
